### ISSUE TITLE
run is not working.

### ISSUE THREAD

**Issue by cyril94440** [icanzilb/TaskQueue#12]
Hi,

I don't know why but I am using Reachability to pause and resume the queue, so I do paused = true when there is no internet connexion, then when internet is back, I do paused = false and run. 

They are task in queue, but for some reasons they are never called, and the finish of the run block is never called. Any idea?

Thanks

**Comment by hamchapman** [comment]
Closing as stale.

@cyril94440 if this is something that you want to keep open then please provide an example that reproduces the behaviour you described. Thanks! 👍
