### ISSUE TITLE
Do the tasks continue to run if the application enters background?

### ISSUE THREAD

**Issue by ahmedk92** [icanzilb/TaskQueue#15]
And if they do, for how long?

It seems to me that the queue is subject to the limited time given by iOS to tasks created by `application.beginBackgroundTaskWithExpirationHandler`, since there is no additional setup required to use it.

**Comment by icanzilb** [comment]
yes, all code in your app is subject to the time that the OS gives to your app. If the OS deactivates your app there's no way to do more work
