### ISSUE TITLE
When do I use queue.run()?

### ISSUE THREAD

**Issue by timigod** [icanzilb/TaskQueue#7]
I'm not sure if this is an actual issue but I was wondering. When is the right time to call `.run()` on a queue?
In your Readme, you always called it after you've added all the tasks you wanted to add. Is it possible to call .run() say in a class initialiser and keep adding tasks to it AFTER. So that it just keeps processing tasks as they come (one after the other)?

**Comment by sasavranic** [comment]
I can help...
Define as many tasks as you want and then make a call to run()
```
queue.tasks += { task 1}
queue.tasks += { task 2}
queue.tasks += { task 3}
queue.tasks += { task 4}
queue.run() <<<<<<
```

**Comment by icanzilb** [comment]
hey @timigod - the queue runs until it has tasks to run, once it runs out of tasks it destroys itself...
